sudo : required
services : docker

script:
  - docker build -t sivakumargollu/elearnapi ./elearning-api
  - docker build -t sivakumargollu/elearn-frontend ./elearning-frontend
  - docker build -t sivakumargollu/elearn-loadbalancer ./elearning-loadbalancer
#Docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
#pushing images to docker
  - docker push sivakumargollu/elearnapi
  - docker push sivakumargollu/elearn-frontend
  - docker push sivakumargollu/elearn-loadbalancer